server.port: 8085

api:
  finnhub:
    token: 'ck4fjm9r01qus81pv3j0ck4fjm9r01qus81pv3jg'
    domain: 'finnhub.io'
    base-url: 'api/v1'
    endpoints:
      stock:
        profile2: '/stock/profile2'
        quote: '/quote'
        symbol: '/stock/symbol'

spring.datasource:
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'admin1234'
spring.jpa:
  show-sql: true
  ## Hibernate Properties
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  # Hibernate ddl auto (create, create-drop, validate, update)
  hibernate.ddl-auto: update # update

spring.sql.init:
  # schema-locations: classpath:ddl/DDL_DROPS.sql, classpath:ddl/DDL_TUSERS.sql, classpath:ddl/DDL_TPOSTS.sql
  mode: always # always